The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
05/27/2024 01:53:10 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: fp16

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'clip_sample_range', 'rescale_betas_zero_snr', 'dynamic_thresholding_ratio', 'thresholding', 'variance_type'} was not found in config. Values will be initialized to default values.
{'latents_std', 'latents_mean'} was not found in config. Values will be initialized to default values.
{'attention_type', 'dropout', 'reverse_transformer_layers_per_block'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "/net/tscratch/people/plgas2000/zzsn-project/scripts/train/train_dreambooth_ziplora_sdxl.py", line 1817, in <module>
    main(args)
  File "/net/tscratch/people/plgas2000/zzsn-project/scripts/train/train_dreambooth_ziplora_sdxl.py", line 1019, in main
    merged_lora_weights_dict = merge_lora_weights(lora_weights, attn_name)
  File "/net/tscratch/people/plgas2000/zzsn-project/scripts/train/ziplora_utils.py", line 137, in merge_lora_weights
    merged_weight = tensors[up_key] @ tensors[down_key]
KeyError: 'unet.unet.down_blocks.1.attentions.0.transformer_blocks.0.attn1.to_q.lora.up.weight'
Traceback (most recent call last):
  File "/net/tscratch/people/plgas2000/.conda/envs/env_zzsn/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/net/people/plgrid/plgas2000/.local/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/net/people/plgrid/plgas2000/.local/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1075, in launch_command
    simple_launcher(args)
  File "/net/people/plgrid/plgas2000/.local/lib/python3.9/site-packages/accelerate/commands/launch.py", line 681, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/net/tscratch/people/plgas2000/.conda/envs/env_zzsn/bin/python', 'scripts/train/train_dreambooth_ziplora_sdxl.py', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0', '--output_dir=./models/ziplora_dog3_style1_cartoon_2024-05-27_01-52-59', '--lora_name_or_path=./models/dreambooth_lora_sdxl_dog3_subject_2024-05-27_01-28-58', '--instance_prompt=a photo of sks dog', '--instance_data_dir=./dataset/dreambooth-main/dataset/dog3', '--lora_name_or_path_2=./models/dreambooth_lora_sdxl_style1_cartoon_2024-05-26_23-37-49', '--instance_prompt_2=a cat of in crt style', '--instance_data_dir_2=./dataset/styles/style1-cartoon', '--resolution=1024', '--train_batch_size=1', '--learning_rate=5e-5', '--similarity_lambda=0.01', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=100', '--validation_prompt=a photo of sks dog in crt style', '--validation_epochs=10', '--mixed_precision=fp16', '--report_to=tensorboard', '--enable_xformers_memory_efficient_attention', '--logging_dir=./logs/tensorboard_logs']' returned non-zero exit status 1.
